oracle:
  context_tokens: 2048
  temperature: 0.4
  endpoint: "http://localhost:11434"
  active-model: "phi3:mini"
  models:
    -phi3:mini
    #- "gemma3:1b"
    #- "deepseek-r1:8b"

agents:
  max_concurrent: 50
  decision_rate_hz: 10
  perception_batch_size: 32